//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildVersionIncrement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildVersionIncrement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!
        ///You&apos;ve chosen to always apply the Global Settings, this will override any settings in the projects..
        /// </summary>
        internal static string GlobalMessage_alwaysApplyGlobalSettings {
            get {
                return ResourceManager.GetString("GlobalMessage_alwaysApplyGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_AssemblyInfoFilename.
        /// </summary>
        internal static string GlobalVarName_assemblyInfoFilename {
            get {
                return ResourceManager.GetString("GlobalVarName_assemblyInfoFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_BuildAction.
        /// </summary>
        internal static string GlobalVarName_buildAction {
            get {
                return ResourceManager.GetString("GlobalVarName_buildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_BuildVersioningStyle.
        /// </summary>
        internal static string GlobalVarName_buildVersioningStyle {
            get {
                return ResourceManager.GetString("GlobalVarName_buildVersioningStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_ConfigurationName.
        /// </summary>
        internal static string GlobalVarName_configurationName {
            get {
                return ResourceManager.GetString("GlobalVarName_configurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_DetectChanges.
        /// </summary>
        internal static string GlobalVarName_detectChanges {
            get {
                return ResourceManager.GetString("GlobalVarName_detectChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_IncrementBeforeBuild.
        /// </summary>
        internal static string GlobalVarName_incrementBeforeBuild {
            get {
                return ResourceManager.GetString("GlobalVarName_incrementBeforeBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_ReplaceNonNumerics.
        /// </summary>
        internal static string GlobalVarName_replaceNonNumerics {
            get {
                return ResourceManager.GetString("GlobalVarName_replaceNonNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_StartDate.
        /// </summary>
        internal static string GlobalVarName_startDate {
            get {
                return ResourceManager.GetString("GlobalVarName_startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_UpdateAssemblyVersion.
        /// </summary>
        internal static string GlobalVarName_updateAssemblyVersion {
            get {
                return ResourceManager.GetString("GlobalVarName_updateAssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_UpdateFileVersion.
        /// </summary>
        internal static string GlobalVarName_updateFileVersion {
            get {
                return ResourceManager.GetString("GlobalVarName_updateFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_UseGlobalSettings.
        /// </summary>
        internal static string GlobalVarName_useGlobalSettings {
            get {
                return ResourceManager.GetString("GlobalVarName_useGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVersion_UseUniversalClock.
        /// </summary>
        internal static string GlobalVarName_useUniversalClock {
            get {
                return ResourceManager.GetString("GlobalVarName_useUniversalClock", resourceCulture);
            }
        }
    }
}
